[tools]
node = "24.13.0"
bun = "1.3.9"
"npm:@angular/cli" = "21.1.4"

[env]
_.path = ["./node_modules/.bin"]

[tasks]
"dev"="ng serve"

"eslint"="ng lint"
"prettier"="prettier --write ."
"format"={ depends=["eslint", "prettier"] }

"build"={ depends=["format"], run="ng build" }
"deploy"={ depends=["build"], run="wrangler deploy" }
